"""Phase 10 coding foundation: bounded data contracts and read-only analysis.

The local analysis runtime reads validated workspace files and returns bounded
facts only. Edit proposals and test plans remain data; this package adds no
file writes, code execution, command runner, or real model provider. Resolve
all project/file paths through the existing ``Workspace``.
"""

from .errors import (
    CodingError,
    CodingLimitError,
    CodingPermissionError,
    CodingProviderError,
    CodingTimeoutError,
    CodingUnsupportedOperationError,
    CodingValidationError,
    CodingWorkspaceError,
)
from .interfaces import CodingOperation, CodingProvider
from .limits import CodingLimits
from .mock import MockCodingProvider
from .models import (
    AnalyzedCodeFile,
    CodeAnalysisLimitReason,
    CodeAnalysisMethod,
    CodeAnalysisRequest,
    CodeAnalysisResult,
    CodeAnalysisStatus,
    CodeChange,
    CodeDiagnostic,
    CodeEditRequest,
    CodeEditResult,
    CodeEditStatus,
    CodeFile,
    CodeFileMetric,
    CodeLanguage,
    CodePatch,
    CodeRegion,
    CodeSkipReason,
    CodeSymbol,
    CodeSymbolKind,
    CodeTestPlanRequest,
    CodeTestPlanResult,
    CodeTestPlanStatus,
    CodingObservation,
    CodingProject,
    DiagnosticSeverity,
    ObservedCodeFile,
    PatchCheckStatus,
    PatchValidationCheck,
    PatchValidationMetadata,
    PatchValidationStatus,
    SkippedCodeFile,
    TestCasePlan,
)
from .runtime import CodingAnalysisRuntime

__all__ = [
    "AnalyzedCodeFile",
    "CodeAnalysisLimitReason",
    "CodeAnalysisMethod",
    "CodeAnalysisRequest",
    "CodeAnalysisResult",
    "CodeAnalysisStatus",
    "CodeChange",
    "CodeDiagnostic",
    "CodeEditRequest",
    "CodeEditResult",
    "CodeEditStatus",
    "CodeFile",
    "CodeFileMetric",
    "CodeLanguage",
    "CodePatch",
    "CodeRegion",
    "CodeSkipReason",
    "CodeSymbol",
    "CodeSymbolKind",
    "CodeTestPlanRequest",
    "CodeTestPlanResult",
    "CodeTestPlanStatus",
    "CodingAnalysisRuntime",
    "CodingError",
    "CodingLimitError",
    "CodingLimits",
    "CodingObservation",
    "CodingOperation",
    "CodingPermissionError",
    "CodingProject",
    "CodingProvider",
    "CodingProviderError",
    "CodingTimeoutError",
    "CodingUnsupportedOperationError",
    "CodingValidationError",
    "CodingWorkspaceError",
    "DiagnosticSeverity",
    "MockCodingProvider",
    "ObservedCodeFile",
    "PatchCheckStatus",
    "PatchValidationCheck",
    "PatchValidationMetadata",
    "PatchValidationStatus",
    "SkippedCodeFile",
    "TestCasePlan",
]
