"""Phase 10 coding foundation: bounded data, read-only analysis, diagnostics.

The local runtime reads validated workspace files and returns bounded facts;
the diagnostics engine consumes only those source snapshots. Edit proposals
and test plans remain data. This package adds no file writes, code execution,
command runner, or real model provider. Resolve paths through ``Workspace``.
"""

from .diagnostics import CodeDiagnosticBatch, CodeDiagnosticsEngine
from .errors import (
    CodingError,
    CodingLimitError,
    CodingPermissionError,
    CodingProviderError,
    CodingTimeoutError,
    CodingUnsupportedOperationError,
    CodingValidationError,
    CodingWorkspaceError,
)
from .interfaces import CodingOperation, CodingProvider
from .limits import CodingLimits
from .mock import MockCodingProvider
from .models import (
    AnalyzedCodeFile,
    CodeAnalysisLimitReason,
    CodeAnalysisMethod,
    CodeAnalysisRequest,
    CodeAnalysisResult,
    CodeAnalysisStatus,
    CodeChange,
    CodeDiagnostic,
    CodeDiagnosticCategory,
    CodeEditRequest,
    CodeEditResult,
    CodeEditStatus,
    CodeFile,
    CodeFileMetric,
    CodeLanguage,
    CodePatch,
    CodeRegion,
    CodeSkipReason,
    CodeSymbol,
    CodeSymbolKind,
    CodeTestPlanRequest,
    CodeTestPlanResult,
    CodeTestPlanStatus,
    CodingObservation,
    CodingProject,
    DiagnosticSeverity,
    ObservedCodeFile,
    PatchCheckStatus,
    PatchValidationCheck,
    PatchValidationMetadata,
    PatchValidationStatus,
    SkippedCodeFile,
    TestCasePlan,
)
from .patches import (
    CodingPatchRuntime,
    PatchApplicationResult,
    PatchApplicationStatus,
    PatchFileResult,
)
from .runtime import CodingAnalysisRuntime

__all__ = [
    "AnalyzedCodeFile",
    "CodeAnalysisLimitReason",
    "CodeAnalysisMethod",
    "CodeAnalysisRequest",
    "CodeAnalysisResult",
    "CodeAnalysisStatus",
    "CodeChange",
    "CodeDiagnostic",
    "CodeDiagnosticBatch",
    "CodeDiagnosticCategory",
    "CodeDiagnosticsEngine",
    "CodeEditRequest",
    "CodeEditResult",
    "CodeEditStatus",
    "CodeFile",
    "CodeFileMetric",
    "CodeLanguage",
    "CodePatch",
    "CodeRegion",
    "CodeSkipReason",
    "CodeSymbol",
    "CodeSymbolKind",
    "CodeTestPlanRequest",
    "CodeTestPlanResult",
    "CodeTestPlanStatus",
    "CodingAnalysisRuntime",
    "CodingPatchRuntime",
    "CodingError",
    "CodingLimitError",
    "CodingLimits",
    "CodingObservation",
    "CodingOperation",
    "CodingPermissionError",
    "CodingProject",
    "CodingProvider",
    "CodingProviderError",
    "PatchApplicationResult",
    "PatchApplicationStatus",
    "PatchFileResult",
    "CodingTimeoutError",
    "CodingUnsupportedOperationError",
    "CodingValidationError",
    "CodingWorkspaceError",
    "DiagnosticSeverity",
    "MockCodingProvider",
    "ObservedCodeFile",
    "PatchCheckStatus",
    "PatchValidationCheck",
    "PatchValidationMetadata",
    "PatchValidationStatus",
    "SkippedCodeFile",
    "TestCasePlan",
]
