"""Durable SQLite task/event storage for the backend application.

SQLite is deliberately used through the standard library so the core remains
dependency-light. Stored task snapshots contain task state/results and
operational metadata; secrets and chain-of-thought are never generated by
this layer.
"""
from __future__ import annotations

import json
import sqlite3
import threading
from pathlib import Path
from typing import Any

from agent_core.events import AgentEvent
from agent_core.tasks import Task


class TaskStore:
    def __init__(self, path: Path) -> None:
        self._path = path
        self._path.parent.mkdir(parents=True, exist_ok=True)
        self._lock = threading.RLock()
        with self._connect() as db:
            db.executescript(
                """
                CREATE TABLE IF NOT EXISTS tasks (
                    id TEXT PRIMARY KEY,
                    created_at TEXT NOT NULL,
                    updated_at TEXT NOT NULL,
                    state TEXT NOT NULL,
                    payload TEXT NOT NULL
                );
                CREATE TABLE IF NOT EXISTS events (
                    event_id TEXT PRIMARY KEY,
                    task_id TEXT,
                    timestamp TEXT NOT NULL,
                    type TEXT NOT NULL,
                    step_id TEXT,
                    payload TEXT NOT NULL
                );
                CREATE INDEX IF NOT EXISTS idx_tasks_updated ON tasks(updated_at DESC);
                CREATE INDEX IF NOT EXISTS idx_events_task ON events(task_id, timestamp);
                CREATE TABLE IF NOT EXISTS approvals (
                    id TEXT PRIMARY KEY,
                    task_id TEXT NOT NULL,
                    step_id TEXT NOT NULL,
                    tool_name TEXT NOT NULL,
                    permission_level INTEGER NOT NULL,
                    reason TEXT NOT NULL,
                    status TEXT NOT NULL,
                    created_at TEXT NOT NULL,
                    decided_at TEXT,
                    UNIQUE(task_id, step_id)
                );
                CREATE INDEX IF NOT EXISTS idx_approvals_task ON approvals(task_id, created_at DESC);
                """
            )

    def _connect(self) -> sqlite3.Connection:
        db = sqlite3.connect(self._path, timeout=10)
        db.row_factory = sqlite3.Row
        return db

    def save_task(self, task: Task) -> None:
        payload = task.model_dump_json()
        with self._lock, self._connect() as db:
            db.execute(
                """INSERT INTO tasks(id,created_at,updated_at,state,payload)
                   VALUES(?,?,?,?,?)
                   ON CONFLICT(id) DO UPDATE SET
                     updated_at=excluded.updated_at,state=excluded.state,payload=excluded.payload""",
                (task.id, task.created_at.isoformat(), task.updated_at.isoformat(),
                 task.state.value, payload),
            )

    def add_event(self, event: AgentEvent) -> None:
        with self._lock, self._connect() as db:
            db.execute(
                """INSERT OR IGNORE INTO events
                   (event_id,task_id,timestamp,type,step_id,payload)
                   VALUES(?,?,?,?,?,?)""",
                (event.event_id, event.task_id, event.timestamp.isoformat(),
                 event.type.value, event.step_id, json.dumps(event.data, ensure_ascii=False)),
            )

    def create_approval(self, approval_id: str, task_id: str, step_id: str, tool_name: str,
                        permission_level: int, reason: str, created_at: str) -> None:
        with self._lock, self._connect() as db:
            db.execute(
                """INSERT OR IGNORE INTO approvals
                   (id,task_id,step_id,tool_name,permission_level,reason,status,created_at)
                   VALUES(?,?,?,?,?,?,?,?)""",
                (approval_id, task_id, step_id, tool_name, permission_level, reason, "PENDING", created_at),
            )

    def decide_approval(self, approval_id: str, approved: bool, decided_at: str) -> bool:
        status = "APPROVED" if approved else "DENIED"
        with self._lock, self._connect() as db:
            cur = db.execute(
                """UPDATE approvals SET status=?, decided_at=?
                   WHERE id=? AND status='PENDING'""",
                (status, decided_at, approval_id),
            )
            return cur.rowcount == 1

    def get_approval(self, approval_id: str) -> dict[str, Any] | None:
        with self._lock, self._connect() as db:
            row = db.execute("SELECT * FROM approvals WHERE id=?", (approval_id,)).fetchone()
        return dict(row) if row else None

    def list_approvals(self, task_id: str | None = None, limit: int = 100) -> list[dict[str, Any]]:
        limit = max(1, min(limit, 500))
        query = "SELECT * FROM approvals"
        args: tuple[Any, ...] = ()
        if task_id:
            query += " WHERE task_id=?"
            args = (task_id,)
        query += " ORDER BY created_at DESC LIMIT ?"
        args += (limit,)
        with self._lock, self._connect() as db:
            return [dict(row) for row in db.execute(query, args).fetchall()]

    def get_task(self, task_id: str) -> Task | None:
        with self._lock, self._connect() as db:
            row = db.execute("SELECT payload FROM tasks WHERE id=?", (task_id,)).fetchone()
        return Task.model_validate_json(row["payload"]) if row else None

    def list_tasks(self, limit: int = 100) -> list[Task]:
        limit = max(1, min(limit, 500))
        with self._lock, self._connect() as db:
            rows = db.execute(
                "SELECT payload FROM tasks ORDER BY updated_at DESC LIMIT ?", (limit,)
            ).fetchall()
        return [Task.model_validate_json(row["payload"]) for row in rows]

    def events(self, task_id: str, limit: int = 200) -> list[dict[str, Any]]:
        limit = max(1, min(limit, 500))
        with self._lock, self._connect() as db:
            rows = db.execute(
                """SELECT event_id,task_id,timestamp,type,step_id,payload
                   FROM events WHERE task_id=? ORDER BY timestamp,event_id LIMIT ?""",
                (task_id, limit),
            ).fetchall()
        return [
            {
                "event_id": row["event_id"], "task_id": row["task_id"],
                "timestamp": row["timestamp"], "type": row["type"],
                "step_id": row["step_id"], "data": json.loads(row["payload"]),
            }
            for row in rows
        ]
